controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_yaw_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: grip_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - gripper_revolute_joint 

