# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: false
    max_acceleration: 0